### ISSUE TITLE
StarRating: Problems with min and max values 

### ISSUE THREAD

**Issue by Bhoft** [kartik-v/yii2-widget-rating#11]
Hi i have some issues with the StarRating Widget.

First issue I wonder why the form submitted default empty value is "0" instead of ""?

I thought this is because of the default value for "min"
http://plugins.krajee.com/star-rating#option-min

But this isn't the case which shows my second issue.

E.g. if want to have a Rating widget with 4 stars. Where the fist star has the value of "3" and the highest star a value of "4".

With this options i get rendering issues (half highlighted stars etc)

    'pluginOptions' => [
            'min' => 3,
            'max' => 6,
            'stars' => 4,
            'step' => 1,

I have to use this options to get the correct values for the highlighted stars.

    'pluginOptions' => [
            'min' => 2,
            'max' => 6,
            'stars' => 4,            
            'step' => 1,

Now i could think that because of the "min" value of 2 that for no selection the 2 is also posted. But instead there is again the value of "0" in the form post, which is strange.

I guess the starRating couldn't be used with some more special ratings.
e.g. min value of 3 and max of 6. (4 stars)

The only solution could be to set min = 0, max = 4 and stars = 4 and just add the +3 value to the starCaptions with some js expression.  And also add the amount in beforeSave.

**Comment by kartik-v** [comment]
Check the [star highlight logic](http://plugins.krajee.com/star-rating#star-highlight-logic) which will determine the % of star figure highlighted.
