### ISSUE TITLE
have an design issue when creating a custom theme

### ISSUE THREAD

**Issue by Bhoft** [kartik-v/yii2-widget-rating#12]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-rating.
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/rating).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] This is not a source plugin (rating) issue. (Those should be directed to the [plugin issues repo](https://github.com/rating/rating/search?q=&type=Issues)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. i have created a custom theme which uses images for the stars
i have minimized the css margins and paddings etc. and saw some line strokes, which are coming from the input field directly.

![image](https://user-images.githubusercontent.com/1777147/34827232-c36a135a-f6d9-11e7-9cd1-d63ab750908a.png)

the image is of course zoomed in.

Fix could be to change the textInput to hiddenInput.
or by css visibility hidden.

**update**
hmm of course if the textInput is used as a fallback when js is disabled then the js code should change the type of the field to hidden.

**Comment by Bhoft** [comment]
I was thinking about this fall back issue as someone also wanted this "fallback mode" on js errors.
https://github.com/kartik-v/bootstrap-star-rating/issues/178#issuecomment-357982019

Maybe it is better to make the rendering of the widget customizable by settings. 
Similar to your Editable widget where you can set the $inputType to change from text to hidden or html5 number element etc.

The input should then be only set to invisible after the js code is executed. 
As the js adds a div.rating-container around the element the following css code should be enough

    .rating-container input {
      visibility: hidden;
    }

**Comment by kartik-v** [comment]
just a suggestion - can you not style your input yourself as per the need by adding your custom CSS class to the input...

**Comment by kartik-v** [comment]
This has been fixed via opacity in the latest plugin release. Note that the plugin does not hide the input for the reason to allow the native `required` attribute validation to be detected and triggered by the browser.

You could always override your input options this way via the widget:

```php
echo StarRating::widget([
     'options' => ['style' => 'display: none']
]);
```
