### ISSUE TITLE
Does bootstrap-star-rating still work with yii2/bootstrap 3

### ISSUE THREAD

**Issue by davidnewcomb** [kartik-v/yii2-widget-rating#14]
yii2-widget-rating uses yii2-bootstrap with uses bootstrap 3.
yii2-widget-rating uses bootstrap-star-rating. The latest version has breaking changes to use bootstrap v4 features.

I did not understand your notes on the BC change for bootstrap-star-rating so can not see if this change is what has broken my rating widget. It no longer seems to attach click() to the hearts.

Could you elaborate the breaking change a bit more in the documentation and how to fix it.

FYI
Link to http://demos.krajee.com/widget-details/rating in Prerequisites is 404.

**Comment by kartik-v** [comment]
Yes it works with yii2 and BS3 ... [check the details here](http://demos.krajee.com/widget-details/star-rating)

**Comment by davidnewcomb** [comment]
Thanks
