### ISSUE TITLE
wrong event names used on the demo page of the StarRating Widget.

### ISSUE THREAD

**Issue by Bhoft** [kartik-v/yii2-widget-rating#15]
Just some small error on the demo page of the StarRating Widget.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-widget-rating.
- [x] This is not an usage question. I confirm having read the [widget documentation and demos](http://demos.krajee.com/widget-details/rating).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x]  This is not a source plugin (rating) issue. (Those should be directed to the [plugin issues repo](https://github.com/rating/rating/search?q=&type=Issues)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. on http://demos.krajee.com/widget-details/star-rating  the events are mentioned like below.
    "rating.change" => "function() { log("rating.change"); }",
    "rating.clear" => "function() { log("rating.clear"); }",
    "rating.reset" => "function() { log("rating.reset"); }",
2. from the source code i see that the events are rating:change, rating:clear etc. as mentioned here:
    http://plugins.krajee.com/star-rating#events

**Comment by kartik-v** [comment]
Thanks ... Yes event naming was changed recently.... Demo Docs will need to be updated.
