### ISSUE TITLE
syntax error, unexpected ']'

### ISSUE THREAD

**Issue by sahilpatel2216** [kartik-v/yii2-widget-rating#6]
there is mistake in init() method.

**Comment by mitwebsitetest** [comment]
Following is working for me

class StarRatingThemeAsset extends AssetBundle
{
    /**
     * @inheritdoc
     */
    public $sourcePath = '@vendor/kartik-v/bootstrap-star-rating';

    /**
     * @inheritdoc
     */
    public $depends = [
        'kartik\rating\StarRatingAsset'
    ];
    
    /**
     * Add star rating theme file
     *
     * @param string $theme the theme file name
     */
    public function addTheme($theme) 
    {
        $this->css[] = "css/theme-{$theme}." . (YII_DEBUG ? "css" : "min.css");
    }
}
