### ISSUE TITLE
error in multiuse

### ISSUE THREAD

**Issue by saini3080** [kartik-v/yii2-widget-rating#9]
i want to use widget multiple times with form but its giving me first widget value only.here is my code 

<?php $form = ActiveForm::begin(); ?>
		<?php

			echo StarRating::widget([
				'model' => $model2,
				'attribute' => 'rating_communication', 
				'name' => 'rating_communication',
				'pluginOptions' => [
					//'displayOnly' => true,
					'size' => 'xs',
					'showClear' => false,
					'defaultCaption' => '{rating} Stars',
					'filledStar' => '<i class="fa fa-star"></i>',
					'emptyStar' => '<i class="fa fa-star-o"></i>',
					'starCaptions' => new JsExpression("function(val){return val == 1 ? val +' Star' : val + ' Stars';}")
					//'theme' => 'krajee-svg',
					//'filledStar' => '<span class="krajee-icon krajee-icon-star"></span>',
					//'emptyStar' => '<span class="krajee-icon krajee-icon-star"></span>'
				]
				//'disabled' => true
			]);
		?>
	</div>
	<div class="col-sm-3">
		<label>Accuracy</label>
	</div>
	<div class="col-sm-9">
		<?php
			echo StarRating::widget([
				'model' => $model2,
				'attribute' => 'rating_accuracy', 
				'name' => 'rating_accuracy',
				'pluginOptions' => [
					'size' => 'xs',
					'showClear' => false,
					'defaultCaption' => '{rating} Stars',
					'filledStar' => '<i class="fa fa-star"></i>',
					'emptyStar' => '<i class="fa fa-star-o"></i>',
					'starCaptions' => new JsExpression("function(val){return val == 1 ? val +' Star' : val + ' Stars';}")
				]
			]);
		?>
	</div>
	<div class="col-sm-3">
		<label>Cleaning</label>
	</div>
	<div class="col-sm-9">
		<?php
			echo StarRating::widget([
				'model' => $model2,
				'attribute' => 'rating_cleaning', 
				'name' => 'rating_cleaning',
				'pluginOptions' => [
					'size' => 'xs',
					'showClear' => false,
					'defaultCaption' => '{rating} Stars',
					'filledStar' => '<i class="fa fa-star"></i>',
					'emptyStar' => '<i class="fa fa-star-o"></i>',
					'starCaptions' => new JsExpression("function(val){return val == 1 ? val +' Star' : val + ' Stars';}")
				]
			]);
		?>
	</div>
	<div class="col-sm-3">
		<label>Location</label>
	</div>
	<div class="col-sm-9">
		<?php	
			echo StarRating::widget([
				'model' => $model2,
				'attribute' => 'rating_location', 
				'name' => 'rating_location',
				'pluginOptions' => [
					'size' => 'xs',
					'showClear' => false,
					'defaultCaption' => '{rating} Stars',
					'filledStar' => '<i class="fa fa-star"></i>',
					'emptyStar' => '<i class="fa fa-star-o"></i>',
					'starCaptions' => new JsExpression("function(val){return val == 1 ? val +' Star' : val + ' Stars';}")
				]
			]);
		?>
	</div>
	<div class="col-sm-3">
		<label>Value</label>
	</div>
	<div class="col-sm-9">
		<?php
			echo StarRating::widget([
				'model' => $model2,
				'attribute' => 'rating_value', 
				'name' => 'rating_value',
				'pluginOptions' => [
					'size' => 'xs',
					'showClear' => false,
					'defaultCaption' => '{rating} Stars',
					'filledStar' => '<i class="fa fa-star"></i>',
					'emptyStar' => '<i class="fa fa-star-o"></i>',
					'starCaptions' => new JsExpression("function(val){return val == 1 ? val +' Star' : val + ' Stars';}")
				]
			]);
		?>
	</div>
	<div class="col-sm-3">
		<label>Check In</label>
	</div>
	<div class="col-sm-9">
		<?php
			echo StarRating::widget([
				'model' => $model2,
				'attribute' => 'rating_checkin', 
				'name' => 'rating_checkin',
				'pluginOptions' => [
					'size' => 'xs',
					'showClear' => false,
					'defaultCaption' => '{rating} Stars',
					'filledStar' => '<i class="fa fa-star"></i>',
					'emptyStar' => '<i class="fa fa-star-o"></i>',
					'starCaptions' => new JsExpression("function(val){return val == 1 ? val +' Star' : val + ' Stars';}")
				]
			]);
		?>
	</div>
	<div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

**Comment by kartik-v** [comment]
this does not seem to be related to widget. It possibly is related to your yii2 model configuration and controller action that is reading these form posted values. You probably are using yii2's mass load functionality and all attributes that you need in mass load must be marked as `safe` in your model.. then you should get all the data via post.
